import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import walletRouter from "./wallet";
import inventoryRouter from "./inventory";
import marketplaceRouter from "./marketplace";
import notificationsRouter from "./notifications";
import activitiesRouter from "./activities";
import reputationRouter from "./reputation";
import achievementsRouter from "./achievements";
import accountBridgeRouter from "./accountBridge";
import ecosystemRouter from "./ecosystem";
import launcherRouter from "./launcher";
import notificationSyncRouter from "./notificationSync";
import appsRouter from "./apps";
import socialRouter from "./social";
import guildRouter from "./guild";
import questsRouter from "./quests";
import mailRouter from "./mail";
import chatRouter from "./chat";
import worldsRouter from "./worlds";
import aiRouter from "./ai";
import craftingRouter from "./crafting";
import characterRouter from "./character";
import combatRouter from "./combat";
import petRouter from "./pets";
import dungeonRouter from "./dungeons";
import bossRouter from "./bosses";
import pvpRouter from "./pvp";
import creatorRouter from "./creator";
import educationRouter from "./education";
import sportsRouter from "./sports";
import businessRouter from "./business";
import landRouter from "./land";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(walletRouter);
router.use(inventoryRouter);
router.use(marketplaceRouter);
router.use(notificationsRouter);
router.use(activitiesRouter);
router.use(reputationRouter);
router.use(achievementsRouter);
router.use(accountBridgeRouter);
router.use(ecosystemRouter);
router.use(launcherRouter);
router.use(notificationSyncRouter);
router.use(appsRouter);
router.use(socialRouter);
router.use(guildRouter);
router.use(questsRouter);
router.use(mailRouter);
router.use(chatRouter);
router.use(worldsRouter);
router.use(aiRouter);
router.use(craftingRouter);
router.use(characterRouter);
router.use(combatRouter);
router.use(petRouter);
router.use(dungeonRouter);
router.use(bossRouter);
router.use(pvpRouter);
router.use(creatorRouter);
router.use(educationRouter);
router.use(sportsRouter);
router.use(businessRouter);
router.use(landRouter);

export default router;
